
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: noticopa_development
test:
  <<: *default
  database: noticopa_test

production:
  host: ec2-54-243-223-22.compute-1.amazonaws.com
  database: d3vl0pc30soag
  user: tmkyxuizstqkek
  password: NVTAuN783tv2hJlkbO4M0ucvup
  encoding: unicode
  pool: 5
