
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: noticopa_development
test:
  <<: *default
  database: noticopa_test

production:
  adapter: postgresql
  host: ec2-54-235-102-235.compute-1.amazonaws.com
  database: dbq7aq05b50dgj
  user: pkbqrhxtkwfagf
  password: M3_2HjFTH2k6YPjTpHj92iAKz4
  encoding: unicode
  port: 5432
  pool: 5
