
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: noticopa_development
test:
  <<: *default
  database: noticopa_test

production:
  host: ec2-54-235-177-62.compute-1.amazonaws.com
  database: de9due87kddt2p
  user: fvjwpiiljcqjyx
  password: 0gnCUq1nKW4JcIbu7f4bEsMXVB
  encoding: unicode
  pool: 5
