# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8b076c14cfb552c3b0a70d692c08dcd0c806ffad566b915e4ea444a23c67b6e12a4f97d04f400325e9f465ebec7ad98bf010352875aa20dc84293b3e5c8603c

test:
  secret_key_base: 5dfcac1399a548ec958d75b4d7f4c0882339c91015ef4e092904a996748a42b9656b6996aa31d845ae00ffaed15cb3c27502279b4c984bde0b331ffe2007e68a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
